# Generated by Django 4.2.5 on 2023-09-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_faq_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-id']},
        ),
    ]
