# Generated by Django 4.2.5 on 2023-10-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0029_remove_hostel_institution_hostel_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='location',
            new_name='address',
        ),
    ]
