# Generated by Django 4.2.5 on 2023-10-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0030_rename_location_hostel_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='distance_from_admin',
        ),
        migrations.AddField(
            model_name='hostel',
            name='wifi',
            field=models.BooleanField(default=False, help_text='Is there free WiFi?'),
        ),
    ]
