# Generated by Django 4.2.5 on 2023-10-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0031_remove_hostel_distance_from_admin_hostel_wifi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='price_range',
            field=models.CharField(blank=True, help_text="Enter price range in the following format 'INR 4500 - INR 6000'", max_length=300),
        ),
    ]
