# Generated by Django 4.2.5 on 2023-10-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0033_alter_hostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
