# Generated by Django 4.2.5 on 2023-10-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0034_alter_hostel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='boys_hostel',
            field=models.BooleanField(default=False, help_text='Is this a boys hostel?'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='girls_hostel',
            field=models.BooleanField(default=False, help_text='Is this a girls hostel?'),
        ),
    ]
